# Generated by Django 4.0.2 on 2022-03-16 19:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('user', 'language')},
        ),
    ]
