# Generated by Django 4.0.2 on 2022-03-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_alter_language_user_alter_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='long_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='short_description',
            new_name='title',
        ),
    ]
