# Generated by Django 4.0.2 on 2022-03-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0005_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'category')},
        ),
    ]
