# Generated by Django 4.0.2 on 2022-03-03 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0009_alter_location_zip_alter_location_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date')),
                ('stop_date', models.DateTimeField(blank=True, null=True, verbose_name='stop date')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('city', 'country')},
        ),
        migrations.RemoveField(
            model_name='location',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='location',
            name='stop_date',
        ),
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
    ]
