# Generated by Django 4.0.2 on 2022-03-03 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0010_timeperiod_alter_location_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeperiod',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='timeperiod',
            name='stop_date',
            field=models.DateField(blank=True, null=True, verbose_name='stop date'),
        ),
    ]
