# Generated by Django 4.0.2 on 2022-03-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0013_baselocation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='baselocation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='baselocation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='baselocation',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='TimePeriod',
        ),
        migrations.DeleteModel(
            name='BaseLocation',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
