# Generated by Django 4.0.2 on 2022-03-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0014_alter_baselocation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.ImageField(default='https://github.com/CMQNordic/Assets/blob/main/images/unknown-person-icon-27.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
