# Generated by Django 4.0.2 on 2022-03-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0015_remove_user_avatar_user_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=150, verbose_name='location'),
        ),
    ]
