# Generated by Django 4.0.2 on 2022-03-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0016_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
