# Generated by Django 4.0.2 on 2022-03-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0017_remove_user_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
