# Generated by Django 4.0.2 on 2022-03-16 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0018_delete_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
