# Generated by Django 4.0.2 on 2022-03-03 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=150, verbose_name='city')),
                ('country', models.CharField(max_length=150, verbose_name='country')),
                ('ZIP', models.CharField(blank=True, default=0, max_length=10, verbose_name='ZIP')),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=6, verbose_name='longitude')),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=6, verbose_name='latitude')),
            ],
            options={
                'unique_together': {('city', 'country')},
            },
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
            ],
        ),
        migrations.CreateModel(
            name='TempLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templocations', to='locations.location')),
                ('timeperiod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templocations', to='locations.timeperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'location', 'timeperiod')},
            },
        ),
        migrations.CreateModel(
            name='BaseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselocations', to='locations.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'location')},
            },
        ),
    ]
