# Generated by Django 4.0.2 on 2022-04-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('city', 'country', 'longitude', 'latitude')},
        ),
    ]
